version: '2'
services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    env_file:
      - ./config/local_env
    links:
      - db:app-db.local.env.chatops.in
    volumes:
      - "../api/:/opt/goldenmemory/api"
    depends_on:
      - db

  db:
    image: "mysql:5.5.53"
    privileged: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=goldenmemory
